### ISSUE TITLE
Binance

### ISSUE THREAD

**Issue by knayt** [rame0/ConversionPro#1]
У Binance при пополнении счета с РФ карты к рублях есть комиссия 1,2%, но курс обмена на крипку выгоднее.
Можно бодавить это, если выбирается покупка с счета Binance, то чтобы эта комиссия учитывалась и на выходи был реальный курс.

**Comment by knayt** [comment]
И нет в выборе BinancePay, это как раз он и есть.

**Comment by rame0** [comment]
1. Пока не актуально. Тем более, что там комиссия меняется постоянно. Сейчас она 4%.
2. BinancePay - это "фиатный баланс". В фильтр бинанс почему то так его выдает.
